FROM golang:alpine AS builder

RUN apk update && apk add --no-cache git

COPY go.mod go.sum .
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o /go/main main.go

FROM alpine:3.20

RUN apk update && apk add --no-cache bash netcat-openbsd
COPY --from=builder /go/main /go/main
COPY ./entrypoint.sh /go/entrypoint.sh
RUN chmod +x /go/entrypoint.sh

ENV PORT=8080
ENV GIN_MODE=release
EXPOSE 8080
WORKDIR /go

ENTRYPOINT ["/go/entrypoint.sh"]
CMD ["/go/main"]
